Converted ComponentImage variables to Ivariables so as to accept json vars
Vazkii/Patchouli pull request #293
Opened 2020-08-18 21:58 UTC by ITotallyExist

I converted the int variables (width, height, ect.) in the image component to ivariables so that this works:
```
{
    "components":[
        {
            "type": "image",
            "image": "image.png",
            "u": "#u_value",
            "v": "#v_value",
            "width": "#width_value",
           ....
        }
    ]
}
```
```
{
	"name": "name",
	"category": "category",
	"sortnum": 0,
	"pages": [
		{
			"type":"template",
			"u_value":"18",
			"v_value":"17",
                        ...
		}
	]
}
```
If the pull request is accepted, ill do this for the other components (i didnt want to go ahead before making sure the changes were wanted)

Also, i updated the gradle version in the gradle-wrapper properties because the old version didn't work with jdk 14

2020-08-18 22:24 UTC, ITotallyExist commented
discovered a bug, will reopen when it is fixed

2020-10-18 04:09 UTC, williewillus requested changes

2020-10-18 04:09 UTC, williewillus commented on src/main/java/vazkii/patchouli/client/book/template/component/ComponentImage.java
> +			textureWidthInt = textureWidth.asNumber().intValue();
add a method that returns an optional number and use `orElse` on that instead of using exceptions

2020-10-18 04:09 UTC, williewillus commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-6.3-bin.zip
revert this

2020-12-18 03:09 UTC, ITotallyExist commented
I forgot about this, ill implement the changes tomorrow.

2021-02-26 00:14 UTC, closed without merging